name: code_geeks
description: "A new Flutter project."

# Prevent the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Define the version and build number for your application
version: 1.0.0+1

# Define the minimum Dart SDK version required for your project
environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work
dependencies:
  adaptive_theme: ^3.6.0
  animate_icons: ^2.0.0
  animated_icon: ^0.0.9
  any_link_preview: ^3.0.1
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.5
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  dropdown_button2: ^2.3.9
  easy_loading_button: ^0.3.2
  equatable: ^2.0.5
  file_picker: ^6.2.0
  firebase_auth: null
  firebase_core: ^2.25.4
  firebase_database: null
  firebase_messaging: null
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_chat_bubble: ^2.0.2
  flutter_facebook_auth: null
  fluttertoast: null
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  glass_kit: ^3.0.0
  glassmorphism: ^3.0.0
  google_fonts: ^6.1.0
  google_sign_in: null
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  loading_btn: ^1.0.3
  lottie: ^3.1.0
  marquee: ^2.2.3
  numberpicker: ^2.1.2
  passwordfield: ^0.2.0
  permission_handler: ^11.3.0
  pinch_zoom: ^2.0.0
  popover: ^0.3.0
  razorpay_flutter: null
  shared_preferences: null
  shimmer: ^3.0.0
  sign_in_button: ^3.2.0
  smooth_page_indicator: ^1.1.0
  timelines: ^0.1.0

# Development dependencies (currently empty)
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# Flutter-specific configuration
flutter:
  # Ensure that Material Icons font is included with your application
  uses-material-design: true

  # Specify assets used in your application
  assets:
    - lib/assets/anim1.gif # Path to directory containing assets
    - lib/assets/anim2.gif
    - lib/assets/logo.png
    - lib/assets/loader.json
    - lib/assets/signup_loader.json
    - lib/assets/community-button-web-banner-templates-illustration-vector.jpg
    - lib/assets/
