name: code_geeks
description: "A new Flutter project."

# Prevent the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Define the version and build number for your application
version: 1.0.0+1

# Define the minimum Dart SDK version required for your project
environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work
dependencies:
  adaptive_theme: ^3.6.0
  bloc: ^8.1.3
  cloud_firestore: ^4.15.5
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_auth: null
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  glass_kit: ^3.0.0
  glassmorphism: ^3.0.0
  google_fonts: ^6.1.0
  google_sign_in: null
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  popover: ^0.3.0
  sign_in_button: ^3.2.0
  smooth_page_indicator: ^1.1.0

# Development dependencies (currently empty)
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# Flutter-specific configuration
flutter:
  # Ensure that Material Icons font is included with your application
  uses-material-design: true

  # Specify assets used in your application
  assets:
    - lib/assets/anim1.gif # Path to directory containing assets
    - lib/assets/anim2.gif
    - lib/assets/logo.png
